language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

install:
  -

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...  # Run all the tests with the race detector enabled
